version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizza_shop
    volumes:
      - postgres_data:/bitnami/postgresql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
